# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('collect', 'collect'), ('comment', 'comment')], max_length=10)),
                ('occur_time', models.TimeField(default=django.utils.timezone.now)),
                ('comment_text', models.CharField(default='', max_length=140)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImagePost')),
            ],
        ),
    ]
