# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occur_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_num', models.IntegerField(default=0)),
                ('collected_num', models.IntegerField(default=0)),
                ('comments_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occur_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
