# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('images', '0008_imagecomment_pub_time'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinecomment',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.MyUser'),
        ),
        migrations.AddField(
            model_name='timelinecomment',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.MyUser'),
        ),
        migrations.AddField(
            model_name='timelinecomment',
            name='timeline_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='comments_id',
            field=models.ManyToManyField(blank=True, to='timeline.TimelineComment'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='image_ids',
            field=models.ManyToManyField(blank=True, to='images.ImagePost'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MyUser'),
        ),
    ]
