# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receives', to='users.MyUser'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='users.MyUser'),
        ),
    ]
