# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_imagecomment_pub_time'),
        ('users', '0002_myuser_created_at'),
        ('timeline', '0002_auto_20170630_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occur_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='comments_id',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='image_ids',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='timelinecomment',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='timelinecomment',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='timelinecomment',
            name='timeline_id',
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('basictimeline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.BasicTimeline')),
            ],
            bases=('timeline.basictimeline',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basictimeline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.BasicTimeline')),
                ('text', models.CharField(default='', max_length=140)),
            ],
            bases=('timeline.basictimeline',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('basictimeline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.BasicTimeline')),
            ],
            bases=('timeline.basictimeline',),
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.DeleteModel(
            name='TimelineComment',
        ),
        migrations.AddField(
            model_name='basictimeline',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImagePost'),
        ),
        migrations.AddField(
            model_name='basictimeline',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.MyUser'),
        ),
        migrations.AddField(
            model_name='basictimeline',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.MyUser'),
        ),
    ]
