# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20170702_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline'),
        ),
    ]
