# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_timeline_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='occur_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
