# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='tag',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='images.ImageTag'),
        ),
    ]
