# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170703_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='series_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
