# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170703_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MyUser'),
        ),
    ]
