# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170703_1225'),
        ('images', '0002_auto_20170703_1224'),
    ]

    operations = [
    ]
