# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170629_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.ImagePost'),
        ),
    ]
