# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imagetag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
