# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20170704_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='series_no',
        ),
        migrations.AddField(
            model_name='tagno',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImageTag'),
        ),
    ]
