# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20170704_1502'),
        ('images', '0003_auto_20170705_0051'),
    ]

    operations = [
    ]
