# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20170629_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='siblings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.ImagePost'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='tags',
            field=models.ManyToManyField(to='images.ImageTag'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='images',
            field=models.ManyToManyField(null=True, to='images.ImagePost'),
        ),
    ]
