# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20170630_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.ImageComment'),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='comments',
            field=models.ManyToManyField(to='images.ImageComment'),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='description',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='siblings',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='siblings',
            field=models.ManyToManyField(to='images.ImagePost'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='images',
            field=models.ManyToManyField(to='images.ImagePost'),
        ),
    ]
