# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20170630_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
