# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_imagecomment_pub_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='imagecomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagecomment',
            name='previous',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='heat',
            new_name='like_num',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='siblings',
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='images',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.ImagePost'),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='store_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ImageComment',
        ),
    ]
