# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20170630_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='store_num',
            new_name='collect_num',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='path',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
