# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20170701_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
