# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20170701_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='tags',
            field=models.ManyToManyField(to='images.ImageTag'),
        ),
    ]
