# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='followings',
            field=models.ManyToManyField(blank=True, to='users.MyUser'),
        ),
    ]
